### ISSUE TITLE
bgr0 decoding failed. gbrp decoded with wrong color

### ISSUE THREAD

**Issue by HolyWu** [vapoursynth/bestsource#23]
[test_bgr0.zip](https://github.com/vapoursynth/bestsource/files/12852961/test_bgr0.zip)
[test_gbrp10le.zip](https://github.com/vapoursynth/bestsource/files/12852963/test_gbrp10le.zip)

```
Error: Failed to retrieve frame 0 with error: Cannot export to planar format for frame 0
```

![gbrp](https://github.com/vapoursynth/bestsource/assets/5151987/5e1d45e7-b0d2-43ae-afbe-d2188fa93637)

**Comment by myrsloik** [comment]
Fixed both
