### ISSUE TITLE
Standalone indexer?

### ISSUE THREAD

**Issue by Selur** [vapoursynth/bestsource#25]
Any plans for a standalone indexer?
Would be nice to have a standalone indexer like ffindex, dgindex,..

**Comment by myrsloik** [comment]
Nope, this is still in the extremely experimental phase and I intend to greatly speed up seeking for many things first.
Note that you can make a simple python script to act as an indexer. Just open the stream in exact mode and it'll write progress to the vs log. Please contribute it if you write a good one.

**Comment by Selur** [comment]
Ah okay, I thought it was kind of ready since it was mentioned in the Vapoursynth doc in the 'Getting Started' 
(http://www.vapoursynth.com/doc/gettingstarted.html)
Thanks for the info.

**Comment by myrsloik** [comment]
BestSource is at least correct unlike FFMS2 at the moment. FFMS2 should improve the correct way soon.
