### ISSUE TITLE
File libp2p/p2p_api.cpp does not exist

### ISSUE THREAD

**Issue by miaoqiz** [vapoursynth/bestsource#26]
Hi there,

Thanks very much for the plugin. 

I have built libp2p based on the instruction of its GitHub repo. 

https://github.com/libp2p/cpp-libp2p

Then when I use "meson build" here, there was an error shown below:

-------------------------------------------------------

ERROR: File libp2p/p2p_api.cpp does not exist.

-------------------------------------------------------

I search for the cpp files in "meson.build", but they are not in "/usr/local/include/libp2p/".

Also, when it is compiled, how can I use "bestsource" as a plugin. "vsrepo" seems to only work on Windows.

Thanks very much and have a good day!

**Comment by 4re** [comment]
This is the correct libp2p -> https://github.com/sekrit-twc/libp2p
It's ugly af but you have to copy that inside this repo following the file structure you see in the meson.build to compile.

**Comment by miaoqiz** [comment]
Cool! Thanks very much!

**Comment by miaoqiz** [comment]
It worked.

Now I have these in the "build" folder;

-------------------------------------------------------

build.ninja            libbestsource.so.p  libp2p_sse41.a.p  meson-logs
compile_commands.json  libp2p_main.a.p     meson-info        meson-private

-------------------------------------------------------

How can I use "bestsource" as "vapoursynth" plugin then?

Thanks very much and have a good day!

**Comment by 4re** [comment]
` libbestsource.so.p`? What OS are you using? Anyways, `meson insstall` should take care of installing it in vapoursynth's plugin directory. In my case it's `/usr/lib64/vapoursynth/libbestsource.so`

**Comment by miaoqiz** [comment]
I am using Ubuntu 22. I will check "/usr/local/lib".

Thanks very much and have a good week!

**Comment by miaoqiz** [comment]
Thanks very much for your help! I have installed "bestsource".
