### ISSUE TITLE
  bsvideosource returns Y8 for CRAM (msvideo1)

### ISSUE THREAD

**Issue by pdr0github** [vapoursynth/bestsource#45]
bsvideosource returns Y8 for CRAM (msvideo1)

ffvideosource in avs+ returns RGB32, appears normal

ffmpeg decodes as PAL8 like gif , ffplay displays normally

http://samples.mplayerhq.hu/V-codecs/CRAM/BARBIE.AVI

**Comment by myrsloik** [comment]
Behold! AV_PIX_FMT_PAL8 support!
