### ISSUE TITLE
Lossless audio sources 24 bit decoded like 32 bit int

### ISSUE THREAD

**Issue by tebasuna51** [vapoursynth/bestsource#49]
Loading this script in VirtualDub2 you can verify it:

> BSAudioSource("6p321.flac")
> #FFAudioSource("6p321.flac")
> #LWLibavAudioSource("6p321.flac")
> AudioDubEx(BlankClip(length=Int(1000*AudioLengthF(last)/Audiorate(last)), width=720, height=720, fps=25), last)
> Info()

The source can be wav, flac, dtsma or thd the output is always 32 bit int, also with FFAudioSource.

LWLibavAudioSource output the correct 24 bit output.
[6p321.zip](https://github.com/vapoursynth/bestsource/files/15091595/6p321.zip)

**Comment by myrsloik** [comment]
Fixed, will release a new version soon

**Comment by tebasuna51** [comment]
Thanks
