### ISSUE TITLE
Indexing is extremely slow

### ISSUE THREAD

**Issue by shssoichiro** [vapoursynth/bestsource#51]
First of all, thank you for the work in speeding up BestSource. Seeking and decoding are now beautifully fast. However, I found that indexing is still extremely slow. On testing with 1080p sources of about 34000 frames, in AVC, HEVC, and AV1 formats, I found that lsmash and ffms2 were both able to index each of the files in less than 2 seconds, while BestSource took nearly 1 minute on the AVC source and nearly 2 minutes on the other sources.

Perhaps this is unavoidable in order to maintain perfect frame accuracy, however I thought it would be worth noting nevertheless.

![Indexing Time](https://github.com/vapoursynth/bestsource/assets/5951392/53b33565-7d35-4d29-8ba8-077fbd09b0c8)

**Comment by Rumbah2** [comment]
For indexing, Bestsource fully decodes the video so it will always be much slower than the other two.

By default it uses a max of 16 threads to decode, you could increase it with threads=XX to increase the performance.
myrsloik warned me that it might break things but till now it worked for me (I only do the indexing with threads=40).

**Comment by myrsloik** [comment]
Look about right if you have a fast ssd and an average cpu. I guess.
