### ISSUE TITLE
Not all frames are read out

### ISSUE THREAD

**Issue by Dendraspis** [vapoursynth/bestsource#54]
Hello,

to make it a bit shorter and instead of copying I simply refer to this issue:
https://github.com/FFMS/ffms2/issues/443

`BestSource` seems to have a similar issue, except it cannot be fixed setting explicit parameter values.

The media info of the sample file provided in the original issue is:  
```
Duration                                 : 00:01:17.760 (00:01:17:19)
Frame rate                               : 25.000
Frame rate                               : 25.000 FPS
FrameRate_Num                            : 25
FrameRate_Den                            : 1
Frame count                              : 1944
```

StaxRip reports via `VapourSynth` using `BestSource` for :
`clip = core.bs.VideoSource(r"A:\_StaxRip-Test\amarec(20240523-1121).avi")`
...and...
`clip = core.bs.VideoSource(r"A:\_StaxRip-Test\amarec(20240523-1121).avi", fpsnum=25, fpsden=1)`
...this:  
![image](https://github.com/vapoursynth/bestsource/assets/50659978/ab8a86be-1314-473c-907c-b2bd0ce8682e)

Please note, that it reports a length of `1:17.320`, which is **440ms** shorter than it should be, which should be caused by the **11 missing frames** on that frame rate.

**Comment by myrsloik** [comment]
Fixed. I tried to be clever and not CFR when the fps was identical. Expect a new test release soon.
