### ISSUE TITLE
Minimum compiler version

### ISSUE THREAD

**Issue by 0tkl** [vapoursynth/bestsource#56]
When bumping from R4 to ^HEAD, Aegisub build will fail on Debian 11 and Ubuntu 20.04. We find out that BestSource introduced [std::to_chars for FP numbers](https://en.cppreference.com/w/cpp/utility/to_chars) since https://github.com/vapoursynth/bestsource/commit/ddaac8dc7c280eea90a816416899a7f9de438764#diff-fe0470628acf368c8971852850ca82394169b0fd8a64c78426663f21ee0ef2a2R1663, and thus requires gcc 11 / clang 14 to build, which is relatively new.
 See [GCC Implementation Status - C++ 17 - Elementary string conversions](https://gcc.gnu.org/onlinedocs/libstdc++/manual/status.html#status.iso.2017), [libc++ C++17 Status - Note - P0067](https://libcxx.llvm.org/Status/Cxx17.html#note-p0067)

Yeah, it's one of the C++17 features implemented **AFTER** gcc/libstdc++ 9 claimed to have “complete support for C++17”

We suggest using the old code as fallback for older compilers. If not, then at least the required compiler version should be clarified in the README.

**Comment by myrsloik** [comment]
C++17 is C++17. Is there even a macro to detect this easily?

**Comment by 0tkl** [comment]
> Is there even a define to detect this easily?

AFAIK, no. Literally I would read `__clang_major__` and `__GNUC__`, but this would be cumbersome, admittedly…

**Comment by myrsloik** [comment]
Fixed I guess, feature test macros are your friend
