### ISSUE TITLE
bsindex.json not being written by default

### ISSUE THREAD

**Issue by NSQY** [vapoursynth/bestsource#6]
Linux 5.18.14
VS R59
bestsource git master

When loading a file with `bs.VideoSource` and with no additional parameters, no index is created. Specifying `cachepath='~/bsindex.json'` does not create a file either, I need to explicitly specify ``cachepath='/home/foo/bsindex.json'``

`core.lsmas.LWLibavSource(file, cachedir=foo)` behaves in much the same way.

**Comment by myrsloik** [comment]
Probably fixed
