### ISSUE TITLE
Frame leak in LWVideoDecoder::GetVideoProperties

### ISSUE THREAD

**Issue by animetosho** [vapoursynth/bestsource#69]
From what I can tell, the [frame obtained here](https://github.com/vapoursynth/bestsource/blob/4f64f790378a991b2ee49ad1d8f44273f33ddbfd/src/videosource.cpp#L289) is never freed.

After adding `av_frame_free(&PropFrame);` later on, my test code which loops on `bs.VideoSource` doesn't seem to leak memory any more.

I suspect the same may apply to `LWAudioDecoder::GetAudioProperties`.

**Comment by animetosho** [comment]
Instead of freeing the frame, it probably makes more sense to cache it, given that it's likely it'll be reused.

I made [this change](https://github.com/animetosho/bestsource/commit/a9822262ffff12dc47fd1fd26061e54885da66e1), which seems to improve performance with getting the first frame.

**Comment by myrsloik** [comment]
Fixed

**Comment by animetosho** [comment]
Thanks!  
Do you see any merit with caching the frame?

**Comment by myrsloik** [comment]
No, no use at all. The basic decoder classes should be kept as simple as possible. Keep in mind that the info returned is itself cached.

**Comment by animetosho** [comment]
I'd argue that caching the frame actually makes the decoder class *simpler*, since it doesn't need to worry about retrieving and managing the frame, whilst logically making more sense to me, as I wouldn't expect `GetVideoProperties` to *modify* the decoder.

And it definitely improves performance by avoiding the need to double decode the first frame (it's actually worse - early frames are [forced to be linearly decoded](https://github.com/vapoursynth/bestsource/blob/16fdf3ed0f9d3843d9bc26750491e31cab007b53/src/videosource.cpp#L1287-L1288), but since the existing decoder is at frame 1, [it can't be re-used](https://github.com/vapoursynth/bestsource/blob/16fdf3ed0f9d3843d9bc26750491e31cab007b53/src/videosource.cpp#L1324) to decode frame 0, so it'll create a new decoder leaving the existing one defunct and hogging a slot).

But I understand if you disagree. Thanks again for the fix!
