### ISSUE TITLE
Option to not unpack channels in BestAudioSource::GetAudio()

### ISSUE THREAD

**Issue by arch1t3cht** [vapoursynth/bestsource#7]
`BestAudioSource::GetAudio()` always unpacks the audio into its separate channels, but some applications want the audio to be packed instead. It'd be very helpful if there was an option that made GetAudio not unpack before returning the data. This could happen via a boolean argument `unpack` to either the GetAudio function or just to the constructor that defaults to true - if it's set to not unpack, the `Data` argument would contain just one larger buffer for the entire packed audio.

**Comment by myrsloik** [comment]
Now there's a packed getaudio too
