### ISSUE TITLE
Build one library, not two?

### ISSUE THREAD

**Issue by Selur** [vapoursynth/bestsource#70]
Is there a way to build just one libbrary and not two? (bestsource.so and libbestsource.so?)
or to configure bestsource.so in a way that it works if libbestsource.so lies next to it and not under  /usr/local/lib/x86_64-linux-gnu ?

**Comment by arch1t3cht** [comment]
You should be able to links statically using `-Ddefault_library=static`. It will still build and install a static `libbestsource`, but `bestsource.so` will work as a standalone file.

**Comment by Selur** [comment]
Thanks, that worked fine!
