### ISSUE TITLE
Failed indexing mkv(av1)

### ISSUE THREAD

**Issue by Selur** [vapoursynth/bestsource#71]
Trying to open [rife.zip](https://github.com/user-attachments/files/17165561/rife.zip)
using:
`clip = core.bs.VideoSource(source="G:/Output/rife.mkv", cachepath="J:/tmp/rife.json", track=0, hwdevice="cuda")`
I get ` VideoSource: Indexing of 'G:\Output\rife.mkv' track #0 failed` any idea why?
Using 'cpu'  instead of 'cuda' works, but my Geforce RTX 4080 should decode av-1 yuv420P10 content without a problem.

**Comment by myrsloik** [comment]
It only happens when zero valid frames can be decoded. Is cuda decoding completely broken using ffmpeg directly?

**Comment by Selur** [comment]
Just tested, decoding works with [R6](https://github.com/vapoursynth/bestsource/releases/tag/R6) but doesn't with [R7](https://github.com/vapoursynth/bestsource/releases/tag/R7).
So yes, this might be a ffmpeg issue.

**Comment by myrsloik** [comment]
The underlying FFmpeg changed from 6.1.x to 7.0.x so that could be a factor too.

**Comment by myrsloik** [comment]
Probably not my fault
