### ISSUE TITLE
cachepath without subdirectories

### ISSUE THREAD

**Issue by Selur** [vapoursynth/bestsource#72]
Setting cache path to `j:\tmp\test.json`, BestSource creates files like: `J:\tmp\test.json\TestClips&Co\files\test.avi.0.bsindex`, would be nice if instead of the whole path simply a hash of the path could be used?

So instead of `J:\tmp\test.json\TestClips&Co\files`\test.avi.0.bsindex` use:
 * `J:\tmp\test.json\<crc32 Hash of Path to input file>.0.bsindex` or 
 * `J:\tmp\test.json\<crc32 Hash of Path to input file><input file name>.0.bsindex` or
 *  `J:\tmp\test.json\<crc32 Hash of Path to input file>\input file name>.0.bsindex`.

Thanks for considering.

**Comment by myrsloik** [comment]
Done
