### ISSUE TITLE
Only portion of dv file shown

### ISSUE THREAD

**Issue by Selur** [vapoursynth/bestsource#74]
A few Hybrid uses noticed that for dv files BestSource only shows part of the clip.
I cut one to show the problem. => [download](https://drive.filejump.com/drive/s/IxqRgCfuoZwGASuW0HJBxul8AdAVrB)
(this does happen with other dv files too)
BestSource only shows portion of dv clip.
Using BestSource I get only 6885 frames while when using LWLibavSource or ffms2 the whole 9653 frames are shown.

Would be nice if this could get fixed, or somehow mentioned in the README what are the limitations of the source filter, so one can know when to not use it. 
Thanks for looking at it.

**Comment by myrsloik** [comment]
I happens because the decoder returns an error instead of saying it needs more packages. So I guess there's some minor corruption triggering it.
So it's either the file or FFmpeg decoder that has an issue.

**Comment by myrsloik** [comment]
variableformat=true
You format changes in the file. Vdub2 will barf out warnings about it. I think it's only a few frames so you may be able to cut out a bit around frame 6886 to fix it too.
Not a bug.

**Comment by Selur** [comment]
Thanks for looking into it.

**Comment by myrsloik** [comment]
Actually it may be possible to simply ignore the offending frames and turn it into VFR. Reopened because there's potential for improvement.

**Comment by myrsloik** [comment]
I probably fixed it. Turns into a single dropped frame (use timecodes or whatever)
