### ISSUE TITLE
Handle format changes instead of using deprecated FFmpeg feature

### ISSUE THREAD

**Issue by myrsloik** [vapoursynth/bestsource#75]
This is needed for future FFmpeg version compatibility.
It will also make it possible to clearly report/scan if a file is constant format on index.

**Comment by myrsloik** [comment]
How to implement it:
Always index all frames without dropping any at all, when indexing also store which format and dimensions every frame has.
Allow the user to select to return only frames that belong to the nth format set.
This has the advantage that even if variable format output is enabled clips can have a constant format if there actually are no format changes.

**Comment by Ammar-Sadaoui** [comment]
unfortunately that there is no alternative to FFmpeg right now
