### ISSUE TITLE
Hopefully a parameter "end_number" will be added for the end number of the image sequence.

### ISSUE THREAD

**Issue by lyturn** [vapoursynth/bestsource#77]
Just like avisynth's ImageReader, it can read any number of images.

**Comment by myrsloik** [comment]
Why do you need an end number? The end is automatically detected based on the image files

**Comment by lyturn** [comment]
I want to use it for a slideshow script. But it can only read two pictures.

**Comment by lyturn** [comment]
Here is my script:

from vapoursynth import core

video = core.bs.VideoSource(source=r'E:\002\001\%02d.jpg')
video = core.std.AssumeFPS(video,fpsnum=1, fpsden=15)
video = haf.ChangeFPS(video, 24000, 1001) 

audio = core.bas.Source(r'E:\Audio\xxx.mp3', track=-1)

audio.set_output(1)
video.set_output(0)

**Comment by myrsloik** [comment]
It's still automatically detected. This issue makes no sense.

**Comment by lyturn** [comment]
Why it only read part of the pictures, it only read 25 pictures (00.jpg-43.jpg).
I am using the latest version.

from vapoursynth import core
from havsfunc import ChangeFPS

video = core.bs.VideoSource(source=r'E:\002\001\%02d.jpg', start_number=0)
video = core.std.AssumeFPS(video,fpsnum=1, fpsden=6.0)
video = ChangeFPS(video, 24000, 1001) 

video.set_output()

**Comment by myrsloik** [comment]
Couldn't reproduce
