### ISSUE TITLE
Cache Rules?

### ISSUE THREAD

**Issue by sdubinsky** [vapoursynth/bestsource#81]
Hi,
I'm getting some weird caching behavior and I want to make sure I understand what's supposed to be happening.  This is the cache that's created after indexing, when you call `bs.VideoSource`.

* Does the script need to finish successfully to write the cache?
* Does loading the same file in a different script invalidate the cache?
* Does loading with different parameters invalidate the cache?

**Comment by myrsloik** [comment]
> Hi, I'm getting some weird caching behavior and I want to make sure I understand what's supposed to be happening. This is the cache that's created after indexing, when you call `bs.VideoSource`.
> 
> * Does the script need to finish successfully to write the cache?

Only the relevant call to bs.VideoSource needs to finish

> * Does loading the same file in a different script invalidate the cache?

No (assuming they have similar enough parameters). Otherwise you will trigger reindexing every time with a shared cache location.

> * Does loading with different parameters invalidate the cache?

Yes, the ones that change the decoded output will invalidate an index.

**Comment by sdubinsky** [comment]
Changing the pipeline seems  to invalidate the cache.  Is that expected?  For example, in the below script, if I remove the Invert line it no longer uses the cache.  I'm running it as `vspipe script.py .`

```
clip = core.bs.VideoSource(source='PisteFinaleshort.mkv', hwdevice='cuda')
clip = clip[900 * 15]
clip = (
    clip.
    std.CropAbs(100, 100, 100, 100)
    .std.Invert()
    .std.ShufflePlanes(planes=[0], colorfamily=vs.GRAY)
    .resize.Spline36(format=vs.RGB24)
)

clip.set_output()
for frame in clip.frames():
    print(frame.props.OCRString)
```

**Comment by sdubinsky** [comment]
Changing the script, for example removing the line `std.Invert()` seems to invalidate the best source cache even though the video and the `VideoSource` line don't change.

**Comment by sdubinsky** [comment]
Sometimes I can even run the script twice in a row without changing anything and it still reindexes.

**Comment by myrsloik** [comment]
No, that definitely shouldn't trigger reindexing. If you can find a reliable way to reproduce it it'd be helpful.

**Comment by sdubinsky** [comment]
It happens reliably for me, I'm not sure what the next steps are in terms of testing though.

**Comment by myrsloik** [comment]
Should be fixed now, was a bug in master.
