### ISSUE TITLE
`showprogress=True` doesn't print indexing progress

### ISSUE THREAD

**Issue by damster101** [vapoursynth/bestsource#84]
As the title says. I might do or expect something wrong, but what I expect is something similar to what `lsmas.LWLibavSource` prints by default: `Creating lwi index file 100%`

**Comment by myrsloik** [comment]
It's printed through the logging system and will only show up by default in vspipe and certain editors.

**Comment by radpopl** [comment]
> It's printed through the logging system and will only show up by default in vspipe and certain editors.

Maybe it would be worth making it so that it displays by default? Sometimes indexing is so slow that it's worth knowing if it works at all.
