### ISSUE TITLE
strange behavahior indexing and seeking VC-1 and HuffYUV video streams

### ISSUE THREAD

**Issue by GilGalaad** [vapoursynth/bestsource#85]
Preface: in my transcoding video pipeline, many times I used intermediate HuffYUV intermediate files, because they are basically lossless all key frames, decoding is veru fast, and they occupy less than half the space of a pure y4m.
When i use bestsource to open such videos, or some VC-1 encoded blu ray, the indexing process is quite slow, but this is totally expected and understandable because ffmpeg can decode them with fewer cores.
But the weird behavior is when you open an indexed file with a software like VirtualDub, and try to seek: every time it fully decodes the stream from frame 0 to the one I am seeking to.
I create the index with a custon python preprocessor and the line
`vs.core.bs.VideoSource(source=path, cachemode=2, cachepath=bsindex_dir, showprogress=True)`
and I open the file with
`vs.core.bs.VideoSource(source=path, cachemode=2, seekpreroll=0, cachepath=path.parent.joinpath("bsindex"))`.

I can't understand why it happens. If the whole stream has to be decoded again, what is the indexing actually doing with those codecs?
And even more wierdly, how can seek be so slow with HuffYUV that is all key frames? I am using that codec for this very reason in the first place :)

I will gladly provide more information if needed.
Thank you for your amazing work :)

**Comment by arch1t3cht** [comment]
This is likely due to an ffmpeg bug that marks every frame of a VC-1 stream as a keyframe, which can't easily be fixed from bestsource's side.

**Comment by GilGalaad** [comment]
thank you for you answer. i supposed that could be an issue on the decoder side, but worths to report it anyway.

in VC-1 the frame type seems to be reported correctly (I/P/B)
![immagine](https://github.com/user-attachments/assets/bec5106e-de95-4e46-8569-eeee9c422302)

on the other side, for HuffYUV, the frame type is always "?".

**Comment by myrsloik** [comment]
Put bs.SetDebugOutput(True) at the top of your script and it will print a lot of debug info to stderr. Post the log here and maybe it'll become obvious why things happen.

**Comment by GilGalaad** [comment]
I apologize in advance if I will be judged as a noob, Python is not really my thing.
I am trying to enable debug as you suggested, but nothing is printed in console except the progress.
This is the script i use for indexing.

```python
import logging as log
import signal
import sys
from pathlib import Path
import vapoursynth as vs

vs.num_threads = 16
vs.core.max_cache_size = 1024 * 8
vs.core.std.LoadPlugin(r"C:\redacted\BestSource.dll")
vs.core.bs.SetDebugOutput(True)

def main():
    if len(sys.argv) < 2:
        log.error("Please provide path to video file")
        exit(1)

    path: Path = Path(sys.argv[1]).absolute()
    if not path.is_file():
        log.error("Video file not found")
        exit(1)

    bsindex_dir = path.parent.joinpath("bsindex")
    vs.core.bs.VideoSource(source=path, cachemode=2, cachepath=bsindex_dir, showprogress=True)

def signal_handler(sig, frame):
    log.error("Caught SIGINT, aborting process")
    exit(1)

if __name__ == "__main__":
    log.basicConfig(level=log.INFO, format="%(message)s")
    signal.signal(signal.SIGINT, signal_handler)
    main()
```

**Comment by myrsloik** [comment]
You have to request frames somewhere. Either using vspipe or clip.get_frame(some different random numbers)

**Comment by GilGalaad** [comment]
I already tried it, without success.
I added some code to extract info from frame number 500 with `frame: VideoFrame = clip.get_frame(500)` as you suggested, and `set_output()` to enable pipe, without any change in the output.
As you can see, vspipe without seeking it's WAY faster
I am sure I am doing something wrong, but can't really figure what, the script is so simple.
I am really sorry, I don't want to bother you, I have been succesfully using VS for so many years without a problem, but I want to understand if there is margin of improvement with those esoteric codecs...

```
D:\iso>python c:\rip\python\bsindex.py video.mkv
VideoFrame
        Format: YUV420P8
        Width: 1920
        Height: 1080
        Readonly: True

<vapoursynth.FrameProps {'_DurationDen': 1000, 'FlipHorizontal': 0, '_FieldBased': 0, '_Transfer': 2, '_SARNum': 1, '_DurationNum': 41, '_SARDen': 1, '_ChromaLocation': 0, 'Rotation': 0, 'RepeatField': 0, '_PictType': 'P', '_Matrix': 2, 'TopFieldFirst': 1, 'FlipVertical': 0, '_Primaries': 2}>

D:\iso>vspipe -c y4m -s 500 -e 510 c:\rip\python\vapour.vpy .
Output 11 frames in 1.65 seconds (6.68 fps)

D:\iso>vspipe -c y4m -s 0 -e 10 c:\rip\python\vapour.vpy .
Output 11 frames in 0.03 seconds (327.31 fps)
```

**Comment by myrsloik** [comment]
Can you post exactly how you encode the huffyuv files so I can easily create my own test files?

**Comment by GilGalaad** [comment]
> Can you post exactly how you encode the huffyuv files so I can easily create my own test files?

The following command will convert the original file called video.mkv into a HuffYUV encoded destination file, discarding all audio streams. Works on ffmpeg 7.x, but should on 6.x too.
`ffmpeg -loglevel warning -stats -y -i video.mkv -map 0:0 -c ffvhuff video_huff.mkv`

**Comment by myrsloik** [comment]
The huffyuv case has a simple explanation: No frames are marked as keyframes. This is probably a ffmpeg bug and should be reported upstream.

**Comment by myrsloik** [comment]
I looked a bit more. It really does appear that huffyuv doesn't touch keyframes at all. Extremely annoying.

I'll probably add a workaround where all frames will be assumed to be keyframes when zero keyframes exist. But please report this upstream so ffmpeg stops shitting out broken files.

**Comment by myrsloik** [comment]
Now for the VC1 from bluray mystery... It seeks but the returned frame never matches the indexed hash. It then retries earlier and earlier positions until 10 failures in a row happen and linear mode is used as a fallback.
It does seem to correctly mark keyframes however. Also an upstream issue but this one has no workaround and with the extremely limited VC1 usage I doubt anyone really cares.

**Comment by GilGalaad** [comment]
Thank you for your investigations :)
