### ISSUE TITLE
Add option to specify yuv output format

### ISSUE THREAD

**Issue by Kurtnoise-zeus** [vapoursynth/bestsource#88]
Hi,

Would it be possible to add an option for Vapoursynth & Avisynthplus in order to specify the yuv format from the input file (like yuv420p or yuv420p10le, etc...) ?

Thanks in advance.

**Comment by DJATOM** [comment]
`core.bs.VideoSource(...).resize.Bicubic(format=vs.YUV420P10)` should do the job.

**Comment by myrsloik** [comment]
No, it's pointless and would be identical to doing format conversion separately.

**Comment by radpopl** [comment]
> Hi,
> 
> Would it be possible to add an option for Vapoursynth & Avisynthplus in order to specify the yuv format from the input file (like yuv420p or yuv420p10le, etc...) ?

AviSynth does the same thing, and better (more options).
